// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///  
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:    return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    } 
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOvVniLbngv9UHLJiDy1q8ZcI8ArAOKo',
    appId: '1:328812248502:web:cfe5d25599497faf351517',
    messagingSenderId: '328812248502',
    projectId: 'finalyear-b2d26',
    authDomain: 'finalyear-b2d26.firebaseapp.com',
    storageBucket: 'finalyear-b2d26.appspot.com',
    measurementId: 'G-VVLM2PJDYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPDl9VVH-EpxJsJ0t3oFHRMTwmUNHxBc',
    appId: '1:328812248502:android:8f21f5d9805285ec351517',
    messagingSenderId: '328812248502',
    projectId: 'finalyear-b2d26',
    storageBucket: 'finalyear-b2d26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxC5NYU0xvtPxT5LR7XOTlD07sB-tS-A',
    appId: '1:328812248502:ios:aaa398da32dcfd22351517',
    messagingSenderId: '328812248502',
    projectId: 'finalyear-b2d26',
    storageBucket: 'finalyear-b2d26.appspot.com',
    iosClientId: '328812248502-ngsiuo5g45a9j4fbqkkndr061469thbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.miic',
  );
}
